name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install open-watcom-v2
      run: curl "https://cdn.dos.zone/custom/ow2.zip" -o ow2.zip && mkdir -p $HOME/sdk && unzip ow2.zip -d $HOME/sdk/ow2
    - name: fix env
      run: sed -i "s|/home/caiiiycuk|$HOME|g" $HOME/sdk/ow2/owsetenv.sh
    - name: build.sh
      run: cd bin && ./build.sh
    - uses: actions/upload-artifact@v4
      name: upload artifact
      with: 
        path: bin
