name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install openwatcom-1.9
      run: curl "https://cdn.dos.zone/custom/openwatcom.zip" -o openwatcom.zip && mkdir -p $HOME/sdk && unzip openwatcom.zip -d $HOME/sdk/openwatcom
    - name: build.sh
      run: cd bin && ./build.sh
    - uses: actions/upload-artifact@v3.1.3
      path: bin
